name: build_JOGDF_linux64


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: build dependencies
        run: |
          sudo apt-get install openjdk-8-jre openjdk-8-jdk
          echo Building ogdf
          cd ogdf
          sudo cmake .
          sudo make -j 1

          echo Building tmap
          cd ../tmap
          sudo cmake .
          sudo make -j 1

          echo Building Java-tmap Interface
          cd ../src
          sudo cmake .
          # make -j 1
      
      - name: build jogdf
        run: |
          mkdir build
          cd build
          sudo cmake .. 
          sudo make -j 1
          sudo cmake --build . --target install -j 1

      - name: Run Test
        # working-directory: api/build/test
        # run: ./CLPTest
        run: echo skipped

      - uses: actions/upload-artifact@v3
        with:
          name: Jogdf_linux64
          path: build/nativ
      
