name: build_JOGDF_win64


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            git
            zip
            
      - name: build dependencies
        run: |
          echo Building ogdf
          cd ogdf
          cmake .
          make -j 1

          echo Building tmap
          # cd ../tmap
          # cmake .
          # make -j 1

          echo Building Java-tmap Interface
          cd ..
          cd src
          cmake .
          #make -j 1
      
      - name: build jogdf
        run: |
          mkdir build
          cd build
          cmake .. 
          cmake -G "MSYS Makefiles" -DTARGET_ARCH=64 ..
          cmake --build . --target install

      - name: Run Test
        # working-directory: api/build/test
        # run: ./CLPTest
        run: echo skipped

      - name: package
        run: |
          cd build/native/
          Compress-Archive -PATH . -Destination Jogdf.zip
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/native/*.zip"
          name: "Jogdf for win64"
          tag: "Jogdf_win64"
      
